---
# Call this playbook with:
#      ansible-playbook -i inventory \
#                       -e "vault_path=~/rhisbuilder_vault.yml" \
#                       --limit containerhosts \
#                       --vault-password-file=<your vault password file path> \
#                       containerhost_tang.yml


- name: "Install Tang Container on targets"
  hosts: containerhosts
  become: true
  gather_facts: true

  tasks:

    - name: "Load the vault variables"
      ansible.builtin.include_vars:
        file: "{{ vault_path }}"

    - name: "Apply role tang"
      ansible.builtin.include_role:
        name: "tang_container"
